# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

addons:
  artifacts:
    target_paths: /
    paths:
      - $(find $WHEELDIR -newer $WHEELDIR/download_marker -name *.whl | tr [:space:] :)
  apt:
    packages: &base_build
    - libhdf5-serial-dev
    - libnetcdf-dev

python:
  - 3.5
  - 2.7

env:
  global:
    - secure: "mFy/PJrAVKh9Uje1+R8cEOjY8/MDj/qqjn0+FqXCTZPmBMu7RLxTfASMB8QcHfDrJDhH3lEUqkt/uAbGsOKsDIWn/pjKqm6qyvsdw2ISoARommD5lOL3A3Q/Mti1Hz1u4J8CKa0zaGj88NmIyJ2zC8ZyrCl6qS6bTNv7E6A1AIs="
    - WHEELHOUSE="https://unidata-python.s3.amazonaws.com/wheelhouse/index.html"
    - WHEELDIR="wheelhouse/"
    - EXTRAS="test"
  matrix:
    - TASK="coverage"
    - TASK="examples"
    - TASK="lint"

matrix:
  include:
    - python: 2.7
      env: TASK="docs"
      addons:
        apt:
          packages:
            - *base_build
            - pandoc
    - python: 3.3
      env:
    - python: 3.4
      env:
    - python: "3.5-dev"
      env: PRE="--pre"
    - python: nightly
      env: PRE="--pre"
  allow_failures:
    - python: "3.5-dev"
    - python: nightly

before_install:
  - pip install --upgrade pip;
  - if [[ $TASK == "lint" ]]; then
      pip install flake8 pep8-naming;
    elif [[ $TASK == "docs" ]]; then
        pip install -r docs/requirements.txt -f $WHEELHOUSE;
    else
      export EXTRA_PACKAGES="Cython";
      if [[ $TASK == "examples" ]]; then
        export EXTRAS="$EXTRAS,examples";
        export EXTRA_PACKAGES="$EXTRA_PACKAGES nbconvert ipykernel";
        wget https://github.com/OSGeo/proj.4/archive/4.9.2.tar.gz;
        tar xf 4.9.2.tar.gz;
        pushd proj.4-4.9.2;
        ./configure --prefix=$HOME/local;
        make;
        sed -i "" -e s/-I// proj.pc;
        make install;
        export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig";
        export LD_LIBRARY_PATH="$HOME/local/lib";
        pkg-config --modversion proj;
        popd;
      elif [[ $TASK == "coverage" ]]; then
        pip install pytest-cov;
      fi;
      mkdir $WHEELDIR;
      pip download -d $WHEELDIR ".[$EXTRAS]" $EXTRA_PACKAGES -f $WHEELHOUSE $PRE $VERSIONS;
      touch $WHEELDIR/download_marker && ls -lrt $WHEELDIR;
      travis_wait pip wheel -w $WHEELDIR $EXTRA_PACKAGES -f $WHEELHOUSE $PRE $VERSIONS;
      pip install $EXTRA_PACKAGES --upgrade --no-index -f file://$PWD/$WHEELDIR $VERSIONS;
      travis_wait pip wheel ".[$EXTRAS]" -w $WHEELDIR -f $WHEELHOUSE $PRE $VERSIONS;
      rm -f $WHEELDIR/siphon*.whl;
    fi

install:
  - if [[ $TASK != "lint" && $TASK != "docs" ]]; then
      pip install ".[$EXTRAS]" --upgrade --no-index -f file://$PWD/$WHEELDIR $VERSIONS;
      if [[ $TASK == "examples" ]]; then
        python setup.py examples;
      fi;
    fi

script:
  - if [[ $TASK == "lint" ]]; then
      flake8 siphon;
    elif [[ $TASK == "docs" ]]; then
      cd docs;
      make html 2>docs.log;
      if [ -s docs.log ]; then
        echo Doc build produced warnings or errors:;
        cat docs.log;
        false;
      fi;
    elif [[ $TASK == "examples" ]]; then
      if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
        sed -i -e "s/python3/python2/" examples/notebooks/*.ipynb;
      fi;
      find examples/notebooks/ -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --execute --ExecutePreprocessor.timeout=180 --to=notebook --stdout >| /dev/null;
    elif [[ $TASK == "coverage" ]]; then
      python setup.py test --addopts --cov=siphon;
    else
      python setup.py test;
    fi

after_success:
  - if [[ $TASK == "coverage" ]]; then
      pip install codecov codacy-coverage;
      codecov;
      coverage xml;
      python-codacy-coverage -r coverage.xml;
    fi

deploy:
  provider: pypi
  user: dopplershift
  password:
    secure: RQNuBqUGZHgE7Ux9ud93i8IHiAtjy8mibkYoCbYrY4yhobnMT6cJED33jWyEyVHdQ0GIeAl1PQ7NVl4K9OG0L/KADfVLxEqEBoTu6m2Za5ywBDJChyD3N1XlZT/ix7jEIImrjyfcNLahhH8JLpFrBtIllO7JsMgUo3RtzHwBysg=
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: Unidata/siphon
    python: 3.5
    condition: '$TASK == "coverage"'
    tags: true
